### ISSUE TITLE
Missing a License file?

### ISSUE THREAD

**Issue by kryton** [mattdamon108/rust_graphql_api_boilerplate#1]
Hi.
is it possible to add a license.md to this project?

if you unsure of which to use, the Apache ASL-2.0 or BSD-2 ones is quite good/permissive, but naturally it's your work.
FYI .. the juniper project itself is licensed under the BSD-2 license.

Thanks!

**Comment by mununki** [comment]
Thank your for your suggestion. Honestly I don't know well about the license thing. I'll look at it and put a license file with this chance.

**Comment by mununki** [comment]
#2 Added! thanks.
